### PR TITLE
Create new class DocumentReviewer; updated database to version 28 to …

### LINKED ISSUE #1: create new association/table linking ratings to users who inputed the rating, the associated document, and the rating itself (estimated time: 1-2 days)
The acceptance criteria is that a table exists containing a rating, user ID attribute linking the reviewer who inputted the rating, and a document id field linking to the document that is being scored. We will create a test file and try to create rows within the database and see if that is possible.

### PR DESCRIPTION
**Pull request by YiHanna**
…insert the table; wrote simple method to access DocumentReviewer data; wrote simple test cases to ensure data is inserted into database
ran workflow, all tests passed

### CODE REVIEW

**Review by SpencerLong0624 — APPROVED** [review]
Looks good to me!

**Review by jennnnn-z — COMMENTED** [review]
looks good to me :)

**Review by jennnnn-z — APPROVED** [review]

**Review by jennnnn-z — APPROVED** [review]
looks good to me :)

**Review by aneshas01 — APPROVED** [review]
Looks good to me!

**Pull request merged**
