### PR TITLE
Added front end changes including reviewer scores in the 'Additional Metadata' section when editing a document and showing scores when viewing a document

### PR DESCRIPTION
**Pull request by jennnnn-z**
Resolves Issue #2 . Added dropdown input for scores in the 'Additional Metadata' section when editing document and shows scores when viewing a document.

### CODE REVIEW

**Review by SpencerLong0624 — APPROVED** [review]
LGTM

**Review by YiHanna — APPROVED** [review]
looks guud

**Review by aneshas01 — APPROVED** [review]
Looks good to me!

**Review by YiHanna — APPROVED** [review]
looks gud xd

**Pull request merged**
